export type AboutChapter = {
  id: string;
  kicker: string;
  title: string;
  image: string;
  imageAlt: string;
  focus?: string;
  paragraphs: string[];
};

export const aboutChapters: AboutChapter[] = [
  {
    id: "television-performance",
    kicker: "Television & Performance",
    title: "A familiar face with the instincts of a live performer",
    image: "/images/ACTOR.jpg",
    imageAlt: "Deepak Thimaya during his television and performance career",
    focus: "center 24%",
    paragraphs: [
      "Deepak Thimaya’s public journey is closely tied to the evolution of Kannada television. For nearly three decades, he has worked in front of the camera as a presenter, anchor, interviewer and actor, developing the rare ability to be authoritative without becoming distant. His early television association included Doordarshan, while his long connection with Udaya TV helped make him a familiar presence in homes across Karnataka. The transition from actor to television presenter was not a rejection of performance; it was an expansion of it. The timing, observation and emotional intelligence learned on stage became essential tools when he began addressing a live audience, guiding a conversation or responding to an unpredictable guest.",
      "His range on television has never been limited to one format. He has participated in news magazines, interviews, quiz programmes, current-affairs discussions, educational shows, health programmes, women-centred formats, children’s programmes and entertainment productions. That breadth matters because every genre demands a different kind of communication. A quiz master must create pace and anticipation. An interviewer must listen closely enough to discover the question behind an answer. A current-affairs presenter must make complexity understandable without stripping it of meaning. A children’s programme needs warmth and clarity. Moving among these formats gave Deepak a practical understanding of television as both a creative medium and a public responsibility.",
      "Performance came even earlier. His acting roots reach back to school and theatre, including work with Bangalore Little Theatre. He acted in stage productions, Kannada television serials and cameo appearances in films, learning how character, voice, gesture and silence work together. Theatre also placed him in direct contact with an audience, where there is no edit button and every moment must be earned. That foundation explains much of his later screen presence. Even when presenting factual or political content, he understands rhythm, narrative tension and the importance of holding attention. His ease before the camera is therefore not simply a matter of personality; it is the result of years spent studying how people watch, listen and respond.",
      "Among the programmes associated with his career are Time to Talk, Jedara Bale, Special Reporter and Sanjeevini. These shows placed him across interview, analysis and socially relevant programming, often requiring him to move beyond prepared questions and engage with the substance of an issue. His official biography describes Jedara Bale as a particularly enduring issue-based political interview programme on Kannada television. Whether speaking to public personalities, policy makers or viewers, Deepak’s approach has been built around access: bringing influential people and complicated subjects into a conversation that ordinary audiences can follow. This made his television identity larger than that of a conventional host. He became a mediator between events, ideas and the public.",
      "What connects these experiences is adaptability. Television changed dramatically during his career, moving from a smaller broadcast environment to a crowded, fast-moving media world, yet the central challenge remained the same: earn the audience’s trust. Deepak’s work as an anchor, actor, interviewer, quiz master and producer shows a professional willing to learn the grammar of each new format. He can perform, but he can also facilitate; he can command a studio, but he can also make space for another voice. That combination has allowed him to remain relevant across entertainment, journalism, education and public affairs. For Deepak, the camera has never been only a spotlight. It has been a window through which stories, personalities and important questions can enter public life.",
    ],
  },
  {
    id: "journalism",
    kicker: "Journalism & Public Conversation",
    title: "Curiosity shaped into questions that matter",
    image: "/images/JOURNALIST.jpg",
    imageAlt: "Deepak Thimaya as a journalist and interviewer",
    focus: "center 28%",
    paragraphs: [
      "Journalism has been one of the strongest threads running through Deepak Thimaya’s career. It began during his college years, when he edited a newspaper and discovered that gathering information was only the first step; the real work was deciding what mattered, how it should be explained and why a reader should care. That early experience developed habits that would later serve him across print, television and public speaking: research before opinion, clarity before decoration and curiosity before conclusion. Journalism also gave structure to his many other roles. Even while presenting, producing or analysing, he continued to approach people and events with the reporter’s instinct to look beneath the obvious version of a story.",
      "Over time, he worked as a freelance journalist and columnist with publications named in his official biography, including Deccan Herald, Prajavani, Vijay Karnataka, The Times of India, Mid-Day, Outlook and The Week. Working across different publications meant encountering different audiences, editorial cultures and expectations. Newspaper reporting rewards accuracy and economy; columns allow interpretation and voice; magazines invite context and a longer view. That varied print experience helped Deepak develop a style that could move between immediate events and broader social meaning. It also strengthened the editorial judgement required to distinguish noise from consequence—an increasingly important skill in an age when public attention is constantly contested.",
      "A significant editorial milestone was becoming the first editor of Vijaya Next, a Kannada weekly from the Times of India Group. Launching or leading a publication requires more than writing ability. It involves defining its voice, understanding its readership, identifying stories, guiding contributors and creating a coherent experience from many separate pieces. The editor must balance urgency with accuracy and popular interest with public value. This responsibility reflects a side of Deepak’s career that audiences may not immediately see when they know him primarily as a television personality: behind the visible presenter is an editor accustomed to shaping information, testing arguments and building narratives for a wider community.",
      "His journalism found a natural extension in television interviews and political analysis. Programmes such as Time to Talk, Jedara Bale and Special Reporter created room for questions about governance, policy, personality and public accountability. Interviewing politicians and opinion makers is different from delivering a monologue. It requires preparation, active listening and the confidence to follow an unexpected answer. Deepak’s long engagement with Karnataka’s political and social landscape allowed him to place individual statements within a larger context. His work has included interactions with important state leaders and prominent national figures, while his political analysis has also appeared in Prajavani. In each setting, the purpose has been to translate power and policy into language that viewers and readers can examine for themselves.",
      "The most valuable quality in this part of his work is not certainty but sustained inquiry. Deepak’s journalism sits at the meeting point of information and conversation. He has written, edited, interviewed, moderated and analysed, using each format to ask how public events affect real lives. This approach also explains his later commitment to debate education: journalism and debate share a respect for evidence, opposing views and accountable speech. Both require people to listen before they respond. Across decades of changing media, his work has argued—sometimes explicitly and sometimes through practice—that a healthier public culture depends on better questions. The journalist in Deepak is therefore not one role among many; it is the questioning discipline that informs nearly everything else he does.",
    ],
  },
  {
    id: "filmmaking",
    kicker: "Film, Theatre & Storytelling",
    title: "From the first idea to the final frame",
    image: "/images/FILMMAKER.jpg",
    imageAlt: "Deepak Thimaya working as a filmmaker and storyteller",
    focus: "center 32%",
    paragraphs: [
      "Deepak Thimaya’s filmmaking is best understood as the meeting of several disciplines he had already practised: performance, writing, visual communication, production and audience engagement. Long before directing a feature film, he had learned to think about stories from both sides of the camera. As an actor, he understood what performers need from a director. As a presenter, he understood pace and audience attention. As a journalist, he learned to identify the central truth inside a complicated subject. As a producer, he became familiar with the practical work that turns an idea into something visible. Filmmaking brought all of these abilities together and gave him a larger canvas on which to use them.",
      "His body of work behind the camera includes educational films, business films, biographical films and short features. These forms are sometimes treated as secondary to theatrical cinema, but they demand unusual precision. An educational film must make knowledge memorable. A business film must communicate purpose without losing human interest. A biography must respect a real life while shaping a coherent narrative. A short feature has little time to establish its world and emotional stakes. Working across these categories trained Deepak to begin with the audience and the objective, then choose the tone, structure and visual language that would serve them. It also reinforced his belief that film can do more than entertain: it can explain, preserve, persuade and teach.",
      "His best-known feature-film credit is Neene Bari Neene, a Kannada musical romantic drama released in 2015. Deepak directed the film and produced it with Ashok Kheny. The project featured Anish Tejeshwar, Deepika Kamaiah and Samyukta Hornad, and grew from an existing music album into a full cinematic story. Contemporary coverage described it as his directorial debut and noted the unusual challenge of building the film backwards from songs that audiences already knew. Deepak described the story as contemporary and accessible across age and gender, with women characters who were self-respecting and grounded rather than defined only by the hero. The film demonstrated his willingness to move from television’s immediate pace into the longer, collaborative process of feature direction.",
      "Theatre remains another important part of this creative identity. Deepak began acting from his school days and later worked in major stage productions, including with Bangalore Little Theatre. He has written children’s plays, directed productions and connected theatre with education. In 1992 he established the Academy for Child Theatre to promote the use of theatre in classrooms and learning. This initiative reveals a consistent principle in his work: creative expression becomes more powerful when it helps people discover confidence, imagination and a voice of their own. A stage is not simply a place for polished performers; it can be a laboratory where young people learn cooperation, empathy, language and the courage to be seen.",
      "Across film, television and theatre, Deepak approaches storytelling as a complete process. He is interested in the originating concept, the written structure, the performance, the production system and the experience of the eventual audience. His credits as director, producer, actor, writer and dramatist are therefore connected rather than separate achievements. Each role gives him another way to understand how a story travels from one mind to many. This versatility also allows him to cross boundaries that often divide commercial communication, educational work and art. Whether the result is a feature film, a commissioned production, a television series or a children’s play, the central task remains the same: find the human idea, shape it with discipline and create an experience that stays with people after the screen fades or the curtain falls.",
    ],
  },
  {
    id: "education-verbattle",
    kicker: "Education & Verbattle",
    title: "Helping young minds think, listen and speak with courage",
    image: "/images/verbattle.jpg",
    imageAlt: "Deepak Thimaya guiding students through Verbattle",
    focus: "center 38%",
    paragraphs: [
      "Education in Deepak Thimaya’s work is not confined to a classroom or a conventional lecture. It is built around participation. His approach asks learners to form an idea, test it, listen to disagreement, respond with reason and remain open to a better conclusion. This philosophy found its clearest form in Verbattle, the debate and dialogue platform he founded in 2005. Deepak coined the name by bringing together “verbal” and “battle,” but the purpose was never argument for argument’s sake. The larger goal was to improve the quality of thinking and communication among children and young people, using the energy of competition to cultivate intellectual discipline, confidence and respect for other points of view.",
      "Verbattle developed a distinctive three-team debate format and grew through competitions, academies, workshops and institutional programmes. Its framework places language, logic, democratic values and competitive thinking at the centre. That combination is important. Language helps a student express an idea; logic tests whether the idea can stand; democratic values make room for disagreement; and competition gives the exercise urgency. Deepak’s role extends beyond founding the organisation. He has shaped its philosophy, curriculum, standards and public direction while personally conducting and supervising debates. The platform has expanded from Karnataka to national and international activity, carrying an Indian debate model to participants beyond its original geography.",
      "The educational impact reaches further than competition stages. Verbattle conducts debate coaching, public-speaking programmes, leadership activities, clubs and teacher-training initiatives. In teacher workshops, including documented sessions on debate in education and effective communication, Deepak has worked with educators on using debate as a tool for enquiry and experience-based collective learning. This is a significant shift from treating debate as an extracurricular performance for a few confident students. When teachers bring structured questioning and respectful disagreement into everyday learning, the whole classroom can become more alert. Students learn that an answer is not valuable merely because it is spoken loudly; it becomes valuable when it is supported, understood and tested.",
      "This work also brings together strands from Deepak’s earlier career. Television taught him how to hold attention. Journalism taught him to investigate claims. Theatre taught him presence and empathy. Political interviewing exposed him to disagreement, persuasion and the consequences of public language. Verbattle converts those professional lessons into a learning environment for the next generation. Participants are encouraged to think on their feet, but speed alone is never enough. They must comprehend the topic, listen to opponents, organise evidence, manage time, use language responsibly and respond without losing civility. These are debate skills, yet they are also life skills for classrooms, workplaces, communities and democratic citizenship.",
      "At the heart of Deepak’s identity as an educator is a belief that confidence can be built. A young person may begin with hesitation, an unsteady voice or a fear of being judged. Repeated opportunities to research, speak, fail, reconsider and try again can turn that uncertainty into agency. The same applies to teachers who want new ways to awaken participation. Through Verbattle and his broader training work, Deepak has made education active, public and conversational. He does not position the learner as an empty vessel waiting for information. He treats every learner as a mind capable of argument, imagination and leadership. That may be the most enduring connection across his varied career: he uses communication not merely to attract attention, but to help other people discover the strength and responsibility of their own voice.",
    ],
  },
  {
    id: "entrepreneurship",
    kicker: "Enterprise & Communication",
    title: "Building organisations where creativity becomes action",
    image: "/images/whatsapp-photo.jpeg",
    imageAlt: "Deepak Thimaya as an entrepreneur and communications professional",
    focus: "center center",
    paragraphs: [
      "Deepak Thimaya began his professional career in advertising after college, entering a field where creativity has to work under real constraints. An idea may be imaginative, but it must also solve a problem, speak to a defined audience and produce a result. He worked across concept and design, developing an interest in the complete communication process rather than one isolated task. Advertising became an early training ground for the combination that would define much of his career: creative thinking joined to practical execution. It taught him to translate a complicated identity into a clear message and to understand that every public-facing organisation tells a story, intentionally or otherwise.",
      "That foundation led him to establish enterprises in advertising, brand promotion, marketing, public relations and brand consultancy. These fields overlap, but each asks a different question. Advertising asks how attention can be earned. Marketing considers how an offering reaches the right people. Public relations shapes long-term understanding and trust. Brand consultancy examines the deeper identity that should guide all communication. Deepak’s experience as a journalist, presenter and producer gave him an unusual perspective in this work. He understood not only what an organisation wanted to say, but also how editors, audiences, viewers and communities might receive it. This allowed communication strategy to be connected with culture and human behaviour rather than reduced to slogans.",
      "He is the Managing Director of TV House Network, a company working across television-show production, product promotion and events. Running such an organisation requires the creative and operational sides of media to function together. A programme needs a concept, talent, research and production planning; a promotional project needs positioning and delivery; an event needs logistics, partnerships and a live experience that reflects its purpose. Deepak’s long exposure to television and public platforms gives him the ability to view these projects from several positions at once—as a creator, performer, producer, client adviser and audience member. The result is an entrepreneurial practice rooted in communication rather than separated from it.",
      "His official biography also records his involvement as a director in companies connected with hospitality, healthcare and technology. These sectors may appear distant from media, but they share the need to understand people, systems and service. Deepak’s entrepreneurial path has therefore not followed a single-industry model. It has grown through connected opportunities, partnerships and social concerns. The same instinct is visible in the events and initiatives he has conceptualised and organised. He often works at the point where a message must become an experience—where people do not simply hear about an idea but encounter it through a programme, gathering, campaign or institution.",
      "Entrepreneurship, for Deepak, is also a way of giving structure to imagination. Verbattle required an organisation capable of turning a debate philosophy into competitions and training. Television ideas required teams and production systems. Brand concepts required execution across media. Social initiatives required networks, credibility and sustained effort. In every case, the entrepreneurial task was to move from “this should exist” to “this now works.” That capacity links his business career with his creative and educational work. He is not only a commentator on ideas or a performer of them; he builds vehicles through which they can operate. Across advertising, consultancy, television production, events and enterprise, his work shows that creativity achieves lasting value when it is organised, communicated clearly and carried into the world with consistency.",
    ],
  },
  {
    id: "public-life-creativity",
    kicker: "Public Life & Creative Expression",
    title: "Ideas carried into civic life, art and leadership",
    image: "/images/political.jpg",
    imageAlt: "Deepak Thimaya engaged in public and political conversation",
    focus: "center 32%",
    paragraphs: [
      "Deepak Thimaya’s involvement in public life grows naturally from his work as a journalist, interviewer and debate educator. He has spent years examining how leaders communicate, how policies are explained and how citizens respond. As a political analyst, he has interviewed and interacted with leading politicians in Karnataka as well as prominent figures at the national level. His television work has placed him inside conversations about governance and public responsibility, while his analysis in Prajavani has carried those questions into print. Rather than treating politics as spectacle alone, his strongest work has focused on the relationship between a decision, the people who make it and the public who must live with its consequences.",
      "Programmes such as Time to Talk, Jedara Bale, Special Reporter and Sanjeevini demonstrate the range of this engagement. Some created direct encounters with political and public personalities; others addressed social, health or current-affairs subjects. Deepak’s official biography describes Jedara Bale as a long-running issue-based interview programme associated with Udaya TV. Its premise—looking beyond the news to explore the truth and interests surrounding an issue—reflects his larger method. Public conversation should not end with a headline. It should ask who is affected, what assumptions are being made, which voices are absent and what a responsible response might look like.",
      "He has also participated directly in political and socio-political organisation. His documented career includes service as a vice-president of the Janata Party during the period associated with Dr Vijay Mallya, later public political engagement, and a mentoring role with Samooha Shakti, a socio-political organisation. The significance of this work is not merely partisan. It shows a willingness to move from analysing civic life at a distance to participating in organisation, mobilisation and public dialogue. He has conceptualised and conducted events, addressed large audiences and used his experience as a communicator to bring people around shared questions. His role as Communication Advisor to the Hon’ble Chief Minister of Karnataka further reflects the intersection of media understanding, messaging and public affairs in his career.",
      "Yet public expression is only one part of his creative life. Deepak is also a painter who has worked across media, with paintings displayed and sold through galleries. He has written plays and other material, acted on stage and screen, and remained connected to music. His official biography credits him with creating music and song albums connected with Sri Dr Shivakumara Swamiji of Siddaganga Mutt and Sri Balagangadharanatha Swamiji, as well as writing and singing songs. These activities reveal a personality that does not divide analytical thought from artistic expression. Painting, music and theatre offer different forms of attention: they make room for emotion, symbolism and experience where journalism or policy language may be insufficient.",
      "Taken together, these roles describe a public communicator in the broadest sense. Deepak has worked with facts and performance, institutions and imagination, debate and art. He has been a political analyst, social entrepreneur, mentor, public speaker, writer, painter, dramatist, trainer and motivational voice, while continuing to connect those activities with media and education. The variety is not accidental restlessness. Each role is another route into the same central concern: how people understand themselves, one another and the society they share. His career resists a single label because the problems he engages with do not belong to a single field. They require stories, questions, organisations, images, arguments and action—and his life’s work has been to keep those forms in conversation.",
    ],
  },
];
